// <auto-generated />
// This file normalizes all DateTimeOffset values to UTC before saving to PostgreSQL.
// PostgreSQL stores timestamptz internally as UTC; sending +07:00 offsets
// causes constraint violations and index corruption.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace CinemaTicketBooking.Infrastructure.Persistence;

/// <summary>
/// Ensures all <see cref="DateTimeOffset"/> properties store UTC values,
/// preventing PostgreSQL timezone mismatch errors (e.g., +07:00 offset).
/// </summary>
public class UtcSaveChangesInterceptor : ISaveChangesInterceptor
{
    public ValueTask<InterceptionResult<int>> SavingChangesAsync(
        DbContextEventData eventData,
        InterceptionResult<int> result,
        CancellationToken cancellationToken = default)
    {
        NormalizeDateTimes(eventData.Context);
        return new ValueTask<InterceptionResult<int>>(result);
    }

    public InterceptionResult<int> SavingChanges(
        DbContextEventData eventData,
        InterceptionResult<int> result)
    {
        NormalizeDateTimes(eventData.Context);
        return result;
    }

    private static void NormalizeDateTimes(DbContext? context)
    {
        if (context is null) return;

        foreach (var entry in context.ChangeTracker.Entries())
        {
            if (entry.State is EntityState.Added or EntityState.Modified)
            {
                foreach (var property in entry.Properties)
                {
                    if (property.CurrentValue is null)
                        continue;

                    if (property.Metadata.ClrType == typeof(DateTimeOffset))
                    {
                        var dto = (DateTimeOffset)property.CurrentValue;
                        if (dto.Offset != TimeSpan.Zero)
                        {
                            property.CurrentValue = dto.ToUniversalTime();
                        }
                    }
                    else if (property.Metadata.ClrType == typeof(DateTimeOffset?))
                    {
                        var nullable = (DateTimeOffset?)property.CurrentValue;
                        if (nullable.HasValue && nullable.Value.Offset != TimeSpan.Zero)
                        {
                            property.CurrentValue = nullable.Value.ToUniversalTime();
                        }
                    }
                }
            }
        }
    }
}